using System.ComponentModel.DataAnnotations;

#pragma warning disable CS8618

namespace CustomerApi.Models
{
    public class Customer
    {
 
    [Key]
    public string id { get; set; }      
    public string CustomerField2 { get; set; } 
    public string CustomerField3 { get; set; } 
    public string CustomerField4 { get; set; } 
    public string CustomerField5 { get; set; } 
    public string CustomerField6 { get; set; } 
    public string CustomerField7 { get; set; } 
    public string CustomerField8 { get; set; } 
    public string CustomerField9 { get; set; } 
    public string CustomerField10 { get; set; } 
    public string CustomerField11 { get; set; } 
    public string CustomerField12 { get; set; } 
    public string CustomerField13 { get; set; } 
    public string CustomerField14 { get; set; } 
    public string CustomerField15 { get; set; } 
    public string CustomerField16 { get; set; } 
    public string CustomerField17 { get; set; } 
    public string CustomerField18 { get; set; } 
    public string CustomerField19 { get; set; } 
    public string CustomerField20 { get; set; } 
    public string CustomerField21 { get; set; } 
    public string CustomerField22 { get; set; } 
    public string CustomerField23 { get; set; } 
    public string CustomerField24 { get; set; } 
    public string CustomerField25 { get; set; } 
    public string CustomerField26 { get; set; } 
    public string CustomerField27 { get; set; } 
    public string CustomerField28 { get; set; } 
    public string CustomerField29 { get; set; } 
    public string CustomerField30 { get; set; } 
    public string CustomerField31 { get; set; } 
    public string CustomerField32 { get; set; } 
    public string CustomerField33 { get; set; } 
    public string CustomerField34 { get; set; } 
    public string CustomerField35 { get; set; } 
    public string CustomerField36 { get; set; } 
    public string CustomerField37 { get; set; } 
    public string CustomerField38 { get; set; } 
    public string CustomerField39 { get; set; } 
    public string CustomerField40 { get; set; } 
    public string CustomerField41 { get; set; } 
    public string CustomerField42 { get; set; } 
    public string CustomerField43 { get; set; } 
    public string CustomerField44 { get; set; } 
    public string CustomerField45 { get; set; } 
    public string CustomerField46 { get; set; } 
    public string CustomerField47 { get; set; } 
    public string CustomerField48 { get; set; } 
    public string CustomerField49 { get; set; } 
    public string CustomerField50 { get; set; } 
    public string CustomerField51 { get; set; } 
    public string CustomerField52 { get; set; } 
    public string CustomerField53 { get; set; } 
    public string CustomerField54 { get; set; } 
    public string CustomerField55 { get; set; } 
    public string CustomerField56 { get; set; } 
    public string CustomerField57 { get; set; } 
    public string CustomerField58 { get; set; } 
    public string CustomerField59 { get; set; } 
    public string CustomerField60 { get; set; } 
    public string CustomerField61 { get; set; } 
    public string CustomerField62 { get; set; } 
    public string CustomerField63 { get; set; } 
    public string CustomerField64 { get; set; } 
    public string CustomerField65 { get; set; } 
    public string CustomerField66 { get; set; } 
    public string CustomerField67 { get; set; } 
    public string CustomerField68 { get; set; } 
    public string CustomerField69 { get; set; } 
    public string CustomerField70 { get; set; } 
    public string CustomerField71 { get; set; } 
    public string CustomerField72 { get; set; } 
    public string CustomerField73 { get; set; } 
    public string CustomerField74 { get; set; } 
    public string CustomerField75 { get; set; } 
    public string CustomerField76 { get; set; } 
    public string CustomerField77 { get; set; } 
    public string CustomerField78 { get; set; } 
    public string CustomerField79 { get; set; } 
    public string CustomerField80 { get; set; } 
    public string CustomerField81 { get; set; } 
    public string CustomerField82 { get; set; } 
    public string CustomerField83 { get; set; } 
    public string CustomerField84 { get; set; } 
    public string CustomerField85 { get; set; } 
    public string CustomerField86 { get; set; } 
    public string CustomerField87 { get; set; } 
    public string CustomerField88 { get; set; } 
    public string CustomerField89 { get; set; } 
    public string CustomerField90 { get; set; } 
    public string CustomerField91 { get; set; } 
    public string CustomerField92 { get; set; } 
    public string CustomerField93 { get; set; } 
    public string CustomerField94 { get; set; } 
    public string CustomerField95 { get; set; } 
    public string CustomerField96 { get; set; } 
    public string CustomerField97 { get; set; } 
    public string CustomerField98 { get; set; } 
    public string CustomerField99 { get; set; } 
    public string CustomerField100 { get; set; } 
    public string CustomerField101 { get; set; } 
    public string CustomerField102 { get; set; } 
    public string CustomerField103 { get; set; } 
    public string CustomerField104 { get; set; } 
    public string CustomerField105 { get; set; } 
    public string CustomerField106 { get; set; } 
    public string CustomerField107 { get; set; } 
    public string CustomerField108 { get; set; } 
    public string CustomerField109 { get; set; } 
    public string CustomerField110 { get; set; } 
    public string CustomerField111 { get; set; } 
    public string CustomerField112 { get; set; } 
    public string CustomerField113 { get; set; } 
    public string CustomerField114 { get; set; } 
    public string CustomerField115 { get; set; } 
    public string CustomerField116 { get; set; } 
    public string CustomerField117 { get; set; } 
    public string CustomerField118 { get; set; } 
    public string CustomerField119 { get; set; } 
    public string CustomerField120 { get; set; } 
    public string CustomerField121 { get; set; } 
    public string CustomerField122 { get; set; } 
    public string CustomerField123 { get; set; } 
    public string CustomerField124 { get; set; } 
    public string CustomerField125 { get; set; } 
    public string CustomerField126 { get; set; } 
    public string CustomerField127 { get; set; } 
    public string CustomerField128 { get; set; } 
    public string CustomerField129 { get; set; } 
    public string CustomerField130 { get; set; } 
    public string CustomerField131 { get; set; } 
    public string CustomerField132 { get; set; } 
    public string CustomerField133 { get; set; } 
    public string CustomerField134 { get; set; } 
    public string CustomerField135 { get; set; } 
    public string CustomerField136 { get; set; } 
    public string CustomerField137 { get; set; } 
    public string CustomerField138 { get; set; } 
    public string CustomerField139 { get; set; } 
    public string CustomerField140 { get; set; } 
    public string CustomerField141 { get; set; } 
    public string CustomerField142 { get; set; } 
    public string CustomerField143 { get; set; } 
    public string CustomerField144 { get; set; } 
    public string CustomerField145 { get; set; } 
    public string CustomerField146 { get; set; } 
    public string CustomerField147 { get; set; } 
    public string CustomerField148 { get; set; } 
    public string CustomerField149 { get; set; } 
    public string CustomerField150 { get; set; } 
    public string CustomerField151 { get; set; } 
    public string CustomerField152 { get; set; } 
    public string CustomerField153 { get; set; } 
    public string CustomerField154 { get; set; } 
    public string CustomerField155 { get; set; } 
    public string CustomerField156 { get; set; } 
    public string CustomerField157 { get; set; } 
    public string CustomerField158 { get; set; } 
    public string CustomerField159 { get; set; } 
    public string CustomerField160 { get; set; } 
    public string CustomerField161 { get; set; } 
    public string CustomerField162 { get; set; } 
    public string CustomerField163 { get; set; } 
    public string CustomerField164 { get; set; } 
    public string CustomerField165 { get; set; } 
    public string CustomerField166 { get; set; } 
    public string CustomerField167 { get; set; } 
    public string CustomerField168 { get; set; } 
    public string CustomerField169 { get; set; } 
    public string CustomerField170 { get; set; } 
    public string CustomerField171 { get; set; } 
    public string CustomerField172 { get; set; } 
    public string CustomerField173 { get; set; } 
    public string CustomerField174 { get; set; } 
    public string CustomerField175 { get; set; } 
    public string CustomerField176 { get; set; } 
    public string CustomerField177 { get; set; } 
    public string CustomerField178 { get; set; } 
    public string CustomerField179 { get; set; } 
    public string CustomerField180 { get; set; } 
    public string CustomerField181 { get; set; } 
    public string CustomerField182 { get; set; } 
    public string CustomerField183 { get; set; } 
    public string CustomerField184 { get; set; } 
    public string CustomerField185 { get; set; } 
    public string CustomerField186 { get; set; } 
    public string CustomerField187 { get; set; } 
    public string CustomerField188 { get; set; } 
    public string CustomerField189 { get; set; } 
    public string CustomerField190 { get; set; } 
    public string CustomerField191 { get; set; } 
    public string CustomerField192 { get; set; } 
    public string CustomerField193 { get; set; } 
    public string CustomerField194 { get; set; } 
    public string CustomerField195 { get; set; } 
    public string CustomerField196 { get; set; } 
    public string CustomerField197 { get; set; } 
    public string CustomerField198 { get; set; } 
    public string CustomerField199 { get; set; } 
    public string CustomerField200 { get; set; } 
    public string CustomerField201 { get; set; } 
    public string CustomerField202 { get; set; } 
    public string CustomerField203 { get; set; } 
    public string CustomerField204 { get; set; } 
    public string CustomerField205 { get; set; } 
    public string CustomerField206 { get; set; } 
    public string CustomerField207 { get; set; } 
    public string CustomerField208 { get; set; } 
    public string CustomerField209 { get; set; } 
    public string CustomerField210 { get; set; } 
    public string CustomerField211 { get; set; } 
    public string CustomerField212 { get; set; } 
    public string CustomerField213 { get; set; } 
    public string CustomerField214 { get; set; } 
    public string CustomerField215 { get; set; } 
    public string CustomerField216 { get; set; } 
    public string CustomerField217 { get; set; } 
    public string CustomerField218 { get; set; } 
    public string CustomerField219 { get; set; } 
    public string CustomerField220 { get; set; } 
    public string CustomerField221 { get; set; } 
    public string CustomerField222 { get; set; } 
    public string CustomerField223 { get; set; } 
    public string CustomerField224 { get; set; } 
    public string CustomerField225 { get; set; } 
    public string CustomerField226 { get; set; } 
    public string CustomerField227 { get; set; } 
    public string CustomerField228 { get; set; } 
    public string CustomerField229 { get; set; } 
    public string CustomerField230 { get; set; } 
    public string CustomerField231 { get; set; } 
    public string CustomerField232 { get; set; } 
    public string CustomerField233 { get; set; } 
    public string CustomerField234 { get; set; } 
    public string CustomerField235 { get; set; } 
    public string CustomerField236 { get; set; } 
    public string CustomerField237 { get; set; } 
    public string CustomerField238 { get; set; } 
    public string CustomerField239 { get; set; } 
    public string CustomerField240 { get; set; } 
    public string CustomerField241 { get; set; } 
    public string CustomerField242 { get; set; } 
    public string CustomerField243 { get; set; } 
    public string CustomerField244 { get; set; } 
    public string CustomerField245 { get; set; } 
    public string CustomerField246 { get; set; } 
    public string CustomerField247 { get; set; } 
    public string CustomerField248 { get; set; } 
    public string CustomerField249 { get; set; } 
    public string CustomerField250 { get; set; } 
    public string CustomerField251 { get; set; } 
    public string CustomerField252 { get; set; } 
    public string CustomerField253 { get; set; } 
    public string CustomerField254 { get; set; } 
    public string CustomerField255 { get; set; } 
    public string CustomerField256 { get; set; } 
    public string CustomerField257 { get; set; } 
    public string CustomerField258 { get; set; } 
    public string CustomerField259 { get; set; } 
    public string CustomerField260 { get; set; } 
    public string CustomerField261 { get; set; } 
    public string CustomerField262 { get; set; } 
    public string CustomerField263 { get; set; } 
    public string CustomerField264 { get; set; } 
    public string CustomerField265 { get; set; } 
    public string CustomerField266 { get; set; } 
    public string CustomerField267 { get; set; } 
    public string CustomerField268 { get; set; } 
    public string CustomerField269 { get; set; } 
    public string CustomerField270 { get; set; } 
    public string CustomerField271 { get; set; } 
    public string CustomerField272 { get; set; } 
    public string CustomerField273 { get; set; } 
    public string CustomerField274 { get; set; } 
    public string CustomerField275 { get; set; } 
    public string CustomerField276 { get; set; } 
    public string CustomerField277 { get; set; } 
    public string CustomerField278 { get; set; } 
    public string CustomerField279 { get; set; } 
    public string CustomerField280 { get; set; } 
    public string CustomerField281 { get; set; } 
    public string CustomerField282 { get; set; } 
    public string CustomerField283 { get; set; } 
    public string CustomerField284 { get; set; } 
    public string CustomerField285 { get; set; } 
    public string CustomerField286 { get; set; } 
    public string CustomerField287 { get; set; } 
    public string CustomerField288 { get; set; } 
    public string CustomerField289 { get; set; } 
    public string CustomerField290 { get; set; } 
    public string CustomerField291 { get; set; } 
    public string CustomerField292 { get; set; } 
    public string CustomerField293 { get; set; } 
    public string CustomerField294 { get; set; } 
    public string CustomerField295 { get; set; } 
    public string CustomerField296 { get; set; } 
    public string CustomerField297 { get; set; } 
    public string CustomerField298 { get; set; } 
    public string CustomerField299 { get; set; } 
    public string CustomerField300 { get; set; }
    }
}    

